name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Fmt
        run: |
          go fmt ./...

      - name: Imports
        run: |
          go get golang.org/x/tools/cmd/goimports
          goimports -w ./

      - name: Lint
        run: |
          go get golang.org/x/lint/golint
          golint ./...